version: '3'
services:
  redis:
    image: "redis:5.0"
    command: redis-server
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:5.7"
    build: ./mysql
    environment:
      - MYSQL_DATABASE=clover
      - MYSQL_ROOT_PASSWORD=52.clover
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  clover:
    image: "clover:2.0"
    build: ./clover
    ports:
     - "5000:5000"
    links:
     - mysql:mysql
     - redis:redis
    depends_on:
     - mysql
     - redis
  poppy:
    image: "poppy:2.0"
    build: ./poppy
    ports:
     - "8080:80"
    depends_on:
      - clover


###############################
# docker-compose build
# docker-compose up -d
###############################
## docker-compose 编排记录
  #
  ### 1.下载clover源码,并修改mysql配置
  #```bash
  #git clone https://github.com/52clover/clover.git
  ## 目录 datura->clover
  #
  ## 修改mysql的配置host  clover->config.py
  #MYSQL = {"host": "mysql", 'user': 'root', 'pswd': '52.clover'}
  #
  ## 修改redis的配置host  clover->config.py
  #REDIS_HOST = {"host": "redis"}
  #
  ## 复制clover-docker所有文件到clover文件夹下
  #```
  #
  ### 2.下载poppy源码
  #```bash
  #git clone https://github.com/52clover/poppy.git
  ## 目录 datura->poppy
  #
  ## 复制poppy-clover所有文件到clover文件夹下
  #```
  #
  ### 3.下载镜像包
  #```text
  #1. 下载项目中的datura.tar文件
  #```
  #
  ### 4.镜像包安装到本地
  #```bash
  #docker load -i datura.tar
  #
  ## 查看安装的镜像
  #docker images
  #```
  #
  ### 5.启动容器
  #```bash
  #docker-compose up -d
  #```
#
